### DB Properties ###
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/spring-reddit-clone?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: "root"
    password: ""
   #password: "manager"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
    hibernate:
      ddl-auto: "update"
    show-sql: true
  inizialize: true

### Mail Properties ###
  mail:
    host: "smtp.mailtrap.io"
    port: 25
    username: "125ee385895591"
    password: "ef9c8f447b42a7"
    protocol: "smtp"

